require:
  - rubocop-minitest

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "vendor/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/MethodLength:
  Max: 15
  Exclude:
    - "test/**/*"
    - "lib/claude_agents/cli.rb"
    - "lib/claude_agents/installer.rb"
    - "lib/claude_agents/remover.rb"
    - "lib/claude_agents/symlink_manager.rb"
    - "lib/claude_agents/file_processor.rb"
    - "lib/claude_agents/ui.rb"

Metrics/ClassLength:
  Max: 100
  Exclude:
    - "test/**/*"
    - "lib/claude_agents/cli.rb"
    - "lib/claude_agents/installer.rb"
    - "lib/claude_agents/remover.rb"
    - "lib/claude_agents/symlink_manager.rb"
    - "lib/claude_agents/file_processor.rb"
    - "lib/claude_agents/ui.rb"

Metrics/AbcSize:
  Exclude:
    - "test/**/*"
    - "lib/claude_agents/cli.rb"
    - "lib/claude_agents/installer.rb"
    - "lib/claude_agents/remover.rb"
    - "lib/claude_agents/symlink_manager.rb"
    - "lib/claude_agents/file_processor.rb"
    - "lib/claude_agents/ui.rb"

Metrics/CyclomaticComplexity:
  Exclude:
    - "test/**/*"
    - "lib/claude_agents/cli.rb"
    - "lib/claude_agents/installer.rb"
    - "lib/claude_agents/remover.rb"
    - "lib/claude_agents/symlink_manager.rb"
    - "lib/claude_agents/file_processor.rb"
    - "lib/claude_agents/ui.rb"

Metrics/PerceivedComplexity:
  Exclude:
    - "test/**/*"
    - "lib/claude_agents/cli.rb"
    - "lib/claude_agents/installer.rb"
    - "lib/claude_agents/remover.rb"
    - "lib/claude_agents/symlink_manager.rb"
    - "lib/claude_agents/file_processor.rb"
    - "lib/claude_agents/ui.rb"

Layout/LineLength:
  Max: 100

# Silence metrics noise for tests (allow expressive, verbose test code)
Metrics/BlockLength:
  Exclude:
    - "test/**/*"
    - "Rakefile"

## Test metrics silencing remains below

Metrics/ModuleLength:
  Exclude:
    - "test/**/*"
