AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "vendor/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 100

Layout/LineLength:
  Max: 100
